#!/bin/bash
UUID_FILE="/boot/adsbx-uuid"
if ! [[ -f "$UUID_FILE" ]]; then
    UUID_FILE="/usr/local/share/adsbexchange/adsbx-uuid"
fi
sed -e 's$^$https://www.adsbexchange.com/api/feeders/?feed=$' "$UUID_FILE"
